### ISSUE TITLE
Custom counter disappear in  "Add counters" Windows

### ISSUE THREAD

**Issue by alejandromosquera** [aliostad/PerfIt#20]
When I click on my custom counter in the "Add counters" Windows, my counter disappear, I cant see the counters. What can be the reason? I have Windows 8.1.

Thank you! Great work.

**Comment by aliostad** [comment]
Can you please provide a screenshot of what you mean?

**Comment by alejandromosquera** [comment]
Ok. In the image, the red circle shows a PostsApiRest counter, but when i click on it, this disappear, you can see in the right image in the blue circle
![untitled](https://cloud.githubusercontent.com/assets/872449/6529038/1104b0e6-c3f4-11e4-82ac-493c625262ac.png)

**Comment by RedGhost** [comment]
I have the same issue.

**Comment by aliostad** [comment]
Have you guys, uninstalled the counter? What version of server is it? How can I reproduce it?

**Comment by RedGhost** [comment]
I have uninstalled and installed the counters and they don't seem to show up. The category is there until I click on it. Looking at the registry entry, The address of the first and last counter is the same which makes me think that no counters were created. I followed the guide to set this up to the letter so my code is identical to the setup. I added one perfitfilter with all 4 counters to test and was hoping to have it show up.

**Comment by alejandromosquera** [comment]
I wrote my code according to guide, i think it can be something related with the environment, I have Windows 8.1, my IDE is Visual Studio 2013 and my app is executed with framework 4.5

**Comment by RedGhost** [comment]
I am using WebApi 2.2

**Comment by alejandromosquera** [comment]
yes, me too, i'm using Web Api 2.2

**Comment by RedGhost** [comment]
Might be due to attribute routing?

Found this as the output of the installer:
InstallUtil.exe Information: 0 : Found '0' controllers
InstallUtil.exe Information: 0 : Number of filters: 0
InstallUtil.exe Information: 0 : Built category 'WideOrbit.WOCentral.DMP.API' with 0 items

**Comment by RedGhost** [comment]
Running this code right before PerfItRuntime.Install(Assembly.GetExecutingAssembly()):
var types = Assembly.GetExecutingAssembly().GetExportedTypes().Where(t => typeof(ApiController).IsAssignableFrom(t) && !t.IsAbstract).ToArray();

results in 3 types found so I have no idea what the issue is.

**Comment by RedGhost** [comment]
I just included the project in my code and it fails because of this check: typeof(ApiController).IsAssignableFrom(t)

I am not sure why because the controller is visible in the types list and definitely has a base class of System.Web.Http.ApiController

**Comment by RedGhost** [comment]
I resolved my issue. Looks like the isAssignableFrom was failing because the PerfIt project was using ApiController from a different assembly (not Web Api 2.2).

I fixed this by updating the PerfIt project's target framework to .net 4.5 and updating the Web API nugets.

**Comment by aliostad** [comment]
So Alejandro, can you please confirm whether same fixes your problem?

**Comment by RedGhost** [comment]
This should be easy to reproduce by creating a WebApi 2.2 project and adding the perfit nuget. I'm not sure how to do cross WebApi version compatibility or I would submit a change myself.

**Comment by aliostad** [comment]
Please use assembly binding redirect to fix your version issues.
