### ISSUE TITLE
Instances only available upon initial request

### ISSUE THREAD

**Issue by August2008** [aliostad/PerfIt#22]
I was just wondering...what's the reason for not making all the instances declared on the action via PefItFilterAttribute available right away instead waiting for the route to be hit?

Great project by the way. (Y)

-David

**Comment by aliostad** [comment]
Thanks!

Sorry can you please make it clearer with a code snippet?

**Comment by August2008** [comment]
Hi Ali.
It's a behavior related issue rather than a code issue.. When I install it on any machine and go to PerfMon -> Add Counters -> MyWebApi.dll and look under "Instances of selected object:" list box, which is supposed to show all PefItFilterAttribute instances, it does not show any, unless I hit a particular route.
-David

**Comment by aliostad** [comment]
Well, it is a normal behaviour. So instances are created when a route is hit and should not be a problem. Is it a problem for you?

**Comment by August2008** [comment]
I was load testing my APIs (300+ routes) and had to do a warm up run first and then create PerfMon recorder. Problem no, but would have been more convenient and attractive to not have to do that, unless that's how PerfMon works with generating instances.

**Comment by aliostad** [comment]
I am sorry, this is how win32 counters work.
