### ISSUE TITLE
Problem on install

### ISSUE THREAD

**Issue by alexnaldo** [aliostad/PerfIt#25]
After did all steps the installer show the error:

System.ArgumentException: The savedState dictionary does not contain th
d values and might have been corrupted.
An exception occurred during the Rollback phase of the installation. Th
ion will be ignored and the rollback will continue. However, the machin
ot fully revert to its initial state after the rollback is complete.

**Comment by aliostad** [comment]
which version is this please?

**Comment by alexnaldo** [comment]
The latest version from Install-Package

**Comment by aliostad** [comment]
Please help me to be able to help you.

We are about to release latest version which now you can get by using `install-package perfit -pre` so I need to understand the exact version which you can find in the `packages.config` in your project.

You need to run this in administrative mode. If you do, then create a minimal project to reproduce the problem and sent over. This could be a github project as well.

**Comment by aliostad** [comment]
No response.

**Comment by alexnaldo** [comment]
Sorry. I will try tomorrow.

**Comment by alexnaldo** [comment]
The lastest version the below show an error:

config.MessageHandlers.Add(new PerfItDelegatingHandler());

Where is the PerfItDelegatingHandler class ?

 <package id="PerfIt" version="1.0.0-beta-4" targetFramework="net452" />

**Comment by aliostad** [comment]
It is all gone. It was a smell and had to go so you do not need it, just
define category on the filter itself.
