### ISSUE TITLE
PerfItFilterAttribute - CLS Compliance

### ISSUE THREAD

**Issue by kami1eon** [aliostad/PerfIt#27]
CS3016: There is CLS compliance issue on the Counters collection in the PerfItFilterAttribute.
"Arrays as attribute arguments is not CLS-compliant"

There doesn't seem to be a resolution appart from disabling the check on the whole assembly, which I do not want to do:
[assembly: CLSCompliant(false)]

**Comment by aliostad** [comment]
Sorry what is the actual problem it is causing? Where does this break for you?

**Comment by kami1eon** [comment]
If you have a strict policy and set "Treat errors as warnings" on your project, then it won't build due to CLS compliance issue.

**Comment by kami1eon** [comment]
Build output:

error CS3001: Warning as Error: Argument type 'PerfIt.IInstrumentor' is not CLS-compliant

**Comment by aliostad** [comment]
Hi @kami1eon 
Based on conversations with other .NET developers, this seems to be a redundant nice-to-have which no one cares about anymore.

Initially there were supposed to be many languages on .NET but that did not happen.

So I am afraid this will not be implemented since it is breaking change.
