### ISSUE TITLE
PerfItDelegatingHandler not available

### ISSUE THREAD

**Issue by antonio-ribeiro** [aliostad/PerfIt#30]
Following the documentation...

"
In the  WebApiConfig  class when setting up the configuration, add a PerfIt delegating handler:
config.MessageHandlers.Add(new PerfItDelegatingHandler());
"

The issue is - there's no PerfItDelegatingHandler class in the solution.

Is there a working sample available? Thank you,

António

**Comment by aliostad** [comment]
Sorry, I have to update the documentation... There is no need to use it anymore.
This blog post explains
http://byterot.blogspot.co.uk/2015/05/perfit-decoupled-from-web-api-measure-all-parts-of-your-.net-application-using-perfit-aspnetwebapi-telemetry-etw.html

**Comment by aliostad** [comment]
I have updated the docs.

**Comment by antonio-ribeiro** [comment]
Got It working, thank you,.

**Comment by antonio-ribeiro** [comment]
Still a bug in the installar class - Install method requires two arguments. Can you please provide an updated sample?

public override void Install(IDictionary stateSaver)
{
    base.Install(stateSaver);
    PerfItRuntime.Install(Assembly.GetExecutingAssembly()));
}

**Comment by aliostad** [comment]
Thanks. Would you like to contribute to the docs by sending a PR?
