### ISSUE TITLE
Feature request: ability to set PerfItInterceptor's publishCounters value per instance

### ISSUE THREAD

**Issue by vamurov** [aliostad/PerfIt#37]
Currently all PerfItInterceptor instances read perfit:publishCounters from web.config.
This means that if you want to disable some of the instances, you won't be able to.
It would be nice to be able to set / override the value for each instance of PerfItInterceptor

**Comment by aliostad** [comment]
I have added a feature to turn on and off by `CategoryName` (and not `InstanceName`). Generally `InstanceName` is a runtime concept and not suitable for configuration while `CategoryName` is a design time concept.

In case you share the CategoryName with the library you are using (which normally should not be the case, each project should have its own CategoryName), then change the CategoryName in your project and disable the categoryName for the library you use.

See examples in the README.md in the root of the project or simply on the [homepage](https://github.com/aliostad/PerfIt) in FAQ.

**Comment by vamurov** [comment]
Ali, this is great! Exactly what I needed. The library I'm using has a
different category name, so this is perfect!

Thanks a lot for the rapid response, I'll be able to use this feature in my
next release. The only viable solution so far was to write a logic to
replace the interceptors of the problematic library with fake ones directly
in the Windsor container, which is obviously a hack.

**Comment by aliostad** [comment]
That is awesome! Thanks for making PerfIt better
