### ISSUE TITLE
PerfIt.Castle.Interception does not work with PerfIt version 2.2

### ISSUE THREAD

**Issue by vamurov** [aliostad/PerfIt#39]
This is what I get after upgrading to version 2.2:

Exception: System.MissingMethodException: Method not found: 'Void PerfIt.SimpleInstrumentor.Instrument(System.Action, System.String)'.
at PerfIt.Castle.Interception.PerfItInterceptor.Intercept(IInvocation invocation)
at Castle.DynamicProxy.AbstractInvocation.Proceed()

**Comment by aliostad-asos** [comment]
I have not updated the Castle… Are you using that??

**Comment by vamurov** [comment]
Yes, I'm am. The interception library is perfect for granular measurements.

**Comment by aliostad** [comment]
OK, version 2.3 is out, I just had to cleanup and publish Castle. Let me know how you get on.

**Comment by mwpowellhtx** [comment]
Slightly off topic. See #40, I'm not sure if I am having difficulty with *PerfIt* or *Autofac.Extras.DynamicProxy* or a confluence of both. I am registering both my interceptor, which I simply derive from *PerfItInterceptor* and provide a *categoryName*. The intercepted methods are definitely being called, but I do not seem to be having any interceptions of said methods.

**Comment by aliostad** [comment]
@mwpowellhtx thanks for creating another topic. I need to close this issue since this is fixed.

**Comment by aliostad** [comment]
@vamurov I assume this is fixed now yes?

**Comment by 3686** [comment]
I had this issue, upgrading the nuget packages solved this for me.

In packages.config:

`<package id="PerfIt" version="2.3.0" targetFramework="net451" />`
`<package id="PerfIt.Castle.Interception" version="2.3.0" targetFramework="net451" />`

**Comment by aliostad** [comment]
Fixed
