### ISSUE TITLE
Recommendations for usage with Autofac

### ISSUE THREAD

**Issue by mwpowellhtx** [aliostad/PerfIt#40]
Hello,

I am using [Autofac](http://github.com/autofac/Autofac) for my DI container. I have been learning about [Autofac.Extras.DynamicProxy](http://github.com/autofac/Autofac.Extras.DynamicProxy/), which has some concerns of its own, but I wonder if you had any other recommendations for usage with Autofac?

Using DI conventions, I register my _IInterceptor_? Specifically, I implement a child of _PerfItInterceptor_, which amounts to passing a _categoryName_ to the base class. Registering with _Autofac_ is simple enough. However, what do I do with it in terms of registering the target(s) with the interceptor(s)?

This may be more of an AEDP question, considering the _InterceptedBy_ extension methods want either _Services_, _Types_, or _names_; none of which appears to be that aligned with IInterceptor, which is my confusion at the moment.

Sorry for the breadth of the question, but wanting to connect the dots here.

Thank you!

**Comment by aliostad** [comment]
Hi @mwpowellhtx I suggest a new project to be created for AutoFac since this is for castle. 

For the question, frankly this is an AutoFac question, is it not? If you set up AutoFac interceptor, it should be fairly straightforward to get the PerfIt working.

**Comment by mwpowellhtx** [comment]
@aliostad Re: Autofac DynamicProxy, since there is a specific attribute registration going on, then I would be in favor of a PerfIt project adapting into Autofac. I'd be willing to help with that but I was unable to find a clear registration point, and simply invoking the runtime did not seem to do the trick. I just need a way of identifying the types, bearing in mind possible overlap with AEDP. Perhaps that's a non concern though. Thoughts?

**Comment by aliostad** [comment]
AEDP?

**Comment by mwpowellhtx** [comment]
My alphabet soup for *Autofac.Extras.DynamicProxy*.

**Comment by aliostad** [comment]
Sorry this is old, if still needed I open it again. Apologies for no traction.

**Comment by mwpowellhtx** [comment]
@aliostad No worries; I ran with my own envisioning of the same, [MeasureIt](http://github.com/mwpowellhtx/MeasureIt).
