### ISSUE TITLE
SimpleInstrumentor randomly publishes instrumented callbacks

### ISSUE THREAD

**Issue by mwpowellhtx** [aliostad/PerfIt#46]
What was the thought behind randomly instrumenting callbacks? It seems to me that if you want to instrument a callback, you would want to do this with determinism, not statically. Where am I going wrong with that?

**Comment by aliostad** [comment]
What are you referring to??

**Comment by mwpowellhtx** [comment]
[ShouldInstrument](http://github.com/aliostad/PerfIt/search?utf8=%E2%9C%93&q=SimpleInstrumentor.ShouldInstrument), yields a randomly sampled callback instrumentation. Which for the *PerfIt.Tests* is fine, but falls over in the *PerfIt.Castle.Interception* tests, which expects a callback instrumentation *every time*. Notwithstanding delayed Task, but that's an entirely separate matter, IMO.

**Comment by aliostad** [comment]
Sampling

**Comment by mwpowellhtx** [comment]
Sorry, *Sampling* what? Hertz? Calls per second? As contrasted with stochastic random?

**Comment by aliostad** [comment]
You might want to sample only a portion of requests, especially when you have many requests. Reading the code must be self-explanatory, just look at the usage of `SamplingRate`.

**Comment by mwpowellhtx** [comment]
``return _random.NextDouble() < samplingRate`` does not tell me much. Rate implies something about counts per time unit. It would be more understandable if some Hz calculation was taking place.

**Comment by aliostad** [comment]
This is a simple sampling strategy, initially used by google. Read more on Google's [Dapper paper](http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/36356.pdf).
