### ISSUE TITLE
There are no instrumentationInfos found

### ISSUE THREAD

**Issue by vgary06** [aliostad/PerfIt#59]
Hi,

I always got this exception when I try to install it. (not API 2)
System.InvalidOperationException: There are no instrumentationInfos found by the discoverer!

        `public override void Install(IDictionary stateSaver)
        {
            base.Install(stateSaver);
            PerfItRuntime.Install(Assembly.GetExecutingAssembly(), new FilterDiscoverer());
        }

        public override void Uninstall(IDictionary savedState)
        {
            base.Uninstall(savedState);
            PerfItRuntime.Uninstall(Assembly.GetExecutingAssembly());
        }`

I did what's in the readme but still cannot see the counters in the PerfMon, neither my PerFit web API project name.

Did  I miss something? Because I didn't found any similar Issue in here.

Thanks in advanced.

**Comment by aliostad** [comment]
Would it be possible to send a repro? Just the project with any sensitive stuff removed.
Also which version are you using? And also what instrumenters are you using? Web API, MVC, SimpleInstrumentor?

**Comment by vgary06** [comment]
I just created an asp.net Web Api project with default controller and put the PerfitFilter attribute just like in the readme file. After created the installer like I sent you. In the end I ran cmd and tried to register the counter. Which was totally the same as in the "Getting started" phase.
So it isn't necessary to send any kind of code, because I did what the readme showed me. But on the registration I got the error message in cmd that "System.InvalidOperationException: There are no instrumentationInfos found by the discoverer!"
So, I stuck there and I don't know what kind of instrumentationInfos should I create or add and where.
But if you insist, I can send you just not today, only tomorrow I can.

**Comment by aliostad** [comment]
Assembly loading issues is a common one. This is from Wiki and could be related:

```
A common problem is to encounter FileNotFoundException when registering your counters using InstallUtil. This is more common when your use Web API 2. In any case, this is a problem with InstallUtil not honouring your assembly redirects. To solve the problem (and it is just a workaround), simply copy the assembly redirect directives to InstallUtil.exe.config, run the installation and then remove them.

This has been raised a few times (see the issues, for example #11) but the problem is simply the way InstallUtil works - or rather doesn't.

What I found the best solution is to include a copy of InstallUtil.exe and its custom config (which works for your project by copying content of assemblyBinding section of the web.config) along with your deployables and have a script to install the counter, rather than relying on the standard InstallUtil on the box. These files are small and certainly a good solution.
```

**Comment by vgary06** [comment]
I copied it and filled the config with the assemblyBinding section but I cannot run the InstallUtil because it says that the assemblyBinding is a child element of the configuration and the Windows doesn't support that version.

Another thing, I have to keep those lines in the Installutil.config:
`<startup useLegacyV2RuntimeActivationPolicy="true">
        <supportedRuntime version="v4.0.30319"/>
    </startup>`

Because right now I kept it and under that I copied the assemblyBinding section.
Is it good?

**Comment by aliostad** [comment]
you need you run it from your bin. This is the problem with InstallUtil not perfit.

**Comment by vgary06** [comment]
I did it right now as you said, but the same problem appeared with a little more extra: "the except HRESULT: 0x80131040."
Which means the located assembly's manifest definition does not match the assembly reference. But how's possible?

**Comment by aliostad** [comment]
Can you please join gitter?
https://gitter.im/perfIt-dotnet/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by aliostad** [comment]
OK a couple of things

- you are using PerfIt.WebApi filter against an MVC action. So uninstall Perfit.WebApi and install PerfIt.Mvc. That was the main issue.
- `"GetApiCategory"` not a good name for the category. category is usually the while API hence change it to `"BdNetApiTest"`.
- Use this code for installer:

``` c#
        public override void Install(IDictionary stateSaver)
        {
            base.Install(stateSaver);
            CounterInstaller.InstallStandardCounters("BdNetApiTest");
        }

        public override void Uninstall(IDictionary savedState)
        {
            base.Uninstall(savedState);
            CounterInstaller.Uninstall("BdNetApiTest");
        }
```

That should do the trick. Give it a try and let me know.

**Comment by vgary06** [comment]
Thank you, I'll try it as soon as I can.
Just one thing: Why was a problem to use PerfIt.WebApi on a MVC API project? I used it because 
the exact reason of MVC API should work with PerfIt.WebApi.

**Comment by vgary06** [comment]
Now It's working and can see the counters, but I can't see the instances of the selected objects.
How can I make it showed in the PerfMon?
