### ISSUE TITLE
READme.rd not in sync

### ISSUE THREAD

**Issue by dmumladze** [aliostad/PerfIt#65]
Could you please update README.rd file content to suit the latest API version?

Thx

**Comment by aliostad** [comment]
Sorry can you please point out where it does not, is it installation?

**Comment by dmumladze** [comment]
Yep, it's installation and also it used to be 

`config.MessageHandlers.Add(new PerfitDelegatingHandler());`

But I cannot find that handler anymore. Instead I found this:

`config.MessageHandlers.Add(new PerfitClientDelegatingHandler("ContactsStore.Web.Api"));`

So I'm not sure how to get started for the Web API (ASP.NET 5).

**Comment by aliostad** [comment]
Hi, thank you.
I have incorporated your changes into the README.
With v5 almost out, I had to make lots of other changes, would be good if you could have a look.

Thanks once again.
