### ISSUE TITLE
Support for MVC actions

### ISSUE THREAD

**Issue by aliozgur** [aliostad/PerfIt#7]
I think we can generalize some parts of our code base so that we can support MVC actions as well as Web API methods. We can start by making the following changes

* Change the PerfItRuntime.Install method
* Add an mvc filter attribute
* Remove or modify PerfItContext class 

I already have a stable and working implementation (PerfItMvc) for MVC actions forked from PerfIt so that shall not be a complicated task

**Comment by aliostad** [comment]
This now possible with v1.0.
