### ISSUE TITLE
Sample for using ETW events

### ISSUE THREAD

**Issue by valentinmarinro** [aliostad/PerfIt#71]
Hi @aliostad , is there any samples on how to implement and view the generated ETW events in an WebApi 2 application?

**Comment by aliostad** [comment]
Hmmm, it seems I do not have a sample application or blog or even in the docs. 
But basically, if you use `[PerfIt]` attribute on your actions, ETW events are raised by default.

As you might have noticed, I am bringing PerfIt to aspnetcore too but it is beta. I would like to create samples but this might take a while. As I said, all you need to do is to decorate your actions. Any problems let me know. If you are still not sure how to proceed, let me know so to create a basic sample for you.

May I ask where would you like to store ETW events?

**Comment by valentinmarinro** [comment]
I would like to finally have the events in ELK stack, but from the production server I have no way to connect to our ELK server, so I'm thinking to save them on disk and then copy the file to a different location from where I can import the it with tools like Filebeat and Logstash to Elasticsearch.

If you have another approach or suggestion it will be great, I'm still exploring the solutions / software stacks for instrumentation and metrics on our WebApi 2. 

Your library is great and it was very easy to configure and use, for the performance counters part, but I'm still new to this and maybe I don't know / understand how to use PerfIt for the ETW events.

**Comment by aliostad** [comment]
I can tell you what we do:

We ingest 2TB of logs everyday using [ConveyorBelt](https://github.com/aliostad/ConveyorBelt)... ETW events get transferred using Table Storage Sink (or EventHub) and then ingested by ConveyorBelt. This powers logging and monitoring of +40 teams in ASOS.

If you are in Azure I highly suggest this approach if you do not want to go for ApplicationInsight. Even if you are not in Azure, reading data from Table Storage using CB is easy. Let me know if you need more info.

**Comment by valentinmarinro** [comment]
It's still not clear to me how to save events in log file using PerfIt. I've look at PerfItFilterAttribute source code and in my case TracerTypes is null, so do I have to implement an ITwoStageTracer, or there is a default one already implemented and need to use that?

**Comment by aliostad** [comment]
PerfIt raises [InstrumentationEventSource](https://github.com/aliostad/PerfIt/blob/master/src/PerfIt/InstrumentationEventSource.cs) which then can be captured using various Sinks. If you are looking for File sink, have a look at this package:
https://www.nuget.org/packages/EnterpriseLibrary.SemanticLogging.TextFile/ but I suggest using other sinks - I do not know whether you are in the cloud or not and what your setup is. 

There is a bit more explanation in this [blog](http://byterot.blogspot.co.uk/2015/05/perfit-decoupled-from-web-api-measure-all-parts-of-your-.net-application-using-perfit-aspnetwebapi-telemetry-etw.html) post.

**Comment by valentinmarinro** [comment]
Thanks a lot for the information. I hope I will manage with the links provided.
