### ISSUE TITLE
Duplicate events in ElasticSearch

### ISSUE THREAD

**Issue by valentinmarinro** [aliostad/PerfIt#72]
Hi @aliostad,

I've manage to configure the webapi to log event to both file disk and Elasticsearch using EnterpriseLibrary.SemanticLogging.TextFile and EnterpriseLibrary.SemanticLogging.Elasticsearch, I've set below code in Global.asax.cs Application_Start method:

```
           // log events to file disk
            var fileLogListener = RollingFlatFileLog.CreateListener(
                @"[path]\etw_log.txt",
                5120,
                null,
                RollFileExistsBehavior.Increment,
                RollInterval.None
                );
            fileLogListener.EnableEvents(InstrumentationEventSource.Instance, EventLevel.Informational, Keywords.All);

            // log events to Elasticsearch
            var elasticSearchListener = new ObservableEventListener();
            elasticSearchListener.EnableEvents(InstrumentationEventSource.Instance, EventLevel.Informational, Keywords.All);
            elasticSearchListener.LogToElasticsearch(Environment.MachineName,
                                        "http://localhost:9200",
                                        "MyIndex",
                                        "MyWebApi");

```

But... the problem that I have right now is that in Elastic search I have duplicate records, 6 records for each event, in the log file it is correct only one record per event.

I'm using ElasticSearch version:
```
number | "6.2.3"
build_hash | "c59ff00"
build_date | "2018-03-13T10:06:29.741383Z"
build_snapshot | false
lucene_version | "7.2.1"
minimum_wire_compatibility_version | "5.6.0"
minimum_index_compatibility_version | "5.0.0"
tagline | "You Know, for Search"
```

And PerfIt.WebApi version: 4.0.1, also when I've tried to use Perfit.WebApi 5.0.0-beta7 no events were sent to ElasticSearch.

What am I doing wrong with registering events for ElasticSearch?

**Comment by aliostad** [comment]
On the duplication, frankly that looks like a bug in ES sink... not something that I own or I am familiar with. Also for all machines to have access to ES and write their logs separately into ES, you will soon run into perf and security problems.

On the fact that in beta7 you do not see anything, let me investigate, could be a bug.

**Comment by aliostad** [comment]
Hi,

There were two separate issues that I have fixed now. I am publishing beta8 now.

**Comment by aliostad** [comment]
@valentinmarinro did you get a chance to try the new beta8 or beta9?

**Comment by valentinmarinro** [comment]
Hi @aliostad , yes I've used beta9 with RollingFlatFileLog and SqlDatabaseLog and is working correctly.

One more question, what is the intended purpose for the properties Numeric and Decimal in the InstrumentationContext class?

What I would need is to be able to record more context information like userId, customerId, companyId, I've seen that SqlDatabaseLog  serialize the Payload as JSON, so I would have all these as properties that could be query / make reports directly from SQL Server database. 

```
var databaseListner = SqlDatabaseLog.CreateListener("MyWebApi",
                ConfigurationManager.ConnectionStrings["TraceLogging"].ConnectionString);
databaseListner.EnableEvents(InstrumentationEventSource.Instance, EventLevel.Informational, Keywords.All);
```

Below is a sample of how SqlDatabaseSink serialiaze InstrumentationContext class properties to table column Payload
```
{
	"categoryName": "MyWebApi",
	"instanceName": "TokenController.DoLogin",
	"timeTakenMilli": 439,
	"correlationId": "340c9afa-0e1e-462e-ad49-04cef6daceb7",
	"text1": "POST http://localhost/MyWebApi/v1/token",
	"text2": "Username: User1, UserId: 1, CompanyId: 1",
	"numeric": 0,
	"decima1": 0.0
}
```

**Comment by aliostad** [comment]
For various reasons which I cannot go into, the schema should be fixed, hence you need to cram your info into properties you have. In most cases, this data needs to look at in tools that allow search hence is not a big deal.

**Having said that**, you can inherit from Instrumentation context, add your desired properties and pass that in, and then have a custom tracer that cast it back to your object and stores it (to SQL, etc) as you wish. In fact, you can have the tracer to create another EventSource which has your object as property:

``` csharp
// your new EventSource class
 [EventSource(Name = "MyPerfIt-Instrumentation")]
    public class MyInstrumentationEventSource : EventSource
    {
        public static readonly MyInstrumentationEventSource Instance = new MyInstrumentationEventSource();

   // have the 
     [Event(42, Level = EventLevel.Informational)]
        public void WriteInstrumentationEvent(string categoryName, 
            string instanceName,
            long timeTakenMilli, 
            string correlationId = null,
            string customerId = null,
            string userId = null,
            ...
        {
        ....
      }       
    }

// and here a tracer which outputs your own ETW events
    public class EventSourceTracer : ITwoStageTracer
    {
        public void Finish(object token, 
            long timeTakenMilli, 
            string correlationId = null, 
            InstrumentationContext extraContext = null)
        {
            var context = extraContent as InstrumentationContext;
            MyInstrumentationEventSource.Instance.WriteInstrumentationEvent( ....
        }

```
You just need to add the tracer to instrumentor or filters. There is a new event whenever an instrumentor is created (on `PerfItRuntime`) and you can hook to it and add your tracer in.

Does it make sense?

**Comment by valentinmarinro** [comment]
Hi @aliostad , I think I've implemented all the required classes (see below) and subscribed to the event for instrumentor creation, but with my custom implementation no events are logged to database. as you can see in the last two screenshots the my custom tracer is added to the Tracers collection on the Instrumentor.

```
public class SqlDatabaseInstrumentationContext : InstrumentationContext
{
        public string HttpVerb { get; set; }
        public string Url { get; set; }
        public string Username { get; set; }
        public int? UserId { get; set; }
        public int? UserCompanyId { get; set; }
}
```

```
public class SqlDatabaseInstrumentationContextProvider : IInstrumentationContextProvider
{
	public InstrumentationContext GetContext(HttpActionExecutedContext actionExecutedContext)
	{
		var user = ... get user code here...
		var instrumentationContext = new SqlDatabaseInstrumentationContext
		{
			HttpVerb = actionExecutedContext.Request.Method.Method,
			Url = actionExecutedContext.Request.RequestUri.ToString(),
			Username = user.Username,
			UserId = user.Id,
			UserCompanyId = user.CompanyId
		};

		return instrumentationContext;
	}
}
```

```
public class SqlDatabaseEventSourceTracer : ITwoStageTracer
{
	public void Dispose()
	{
	}

	public void Finish(object token, long timeTakenMilli, string correlationId = null, InstrumentationContext extraContext = null)
	{
		var info = (IInstrumentationInfo)token;
		var context = extraContext as SqlDatabaseInstrumentationContext;
		SqlDatabaseEventSource.Instance.WriteInstrumentationEvent(info.CategoryName,
			info.InstanceName,
			timeTakenMilli,
			correlationId,
			context);
	}

	public object Start(IInstrumentationInfo info)
	{
		return info;
	}
}
```

```
[EventSource(Name = "SqlDatabasePerfIt-Instrumentation")]
public class SqlDatabaseEventSource : EventSource
{
	public static readonly SqlDatabaseEventSource Instance = new SqlDatabaseEventSource();

	private SqlDatabaseEventSource() { }

	[Event(42, Level = EventLevel.Informational)]
	public void WriteInstrumentationEvent(string categoryName,
		string instanceName,
		long timeTakenMilli,
		string correlationId = null,
		SqlDatabaseInstrumentationContext extraContext = null)
	{
		this.WriteEvent(42, 
			categoryName ?? "NoCategory", 
			instanceName ?? "NoInstance", 
			timeTakenMilli,
			correlationId ?? string.Empty, 
			extraContext.HttpVerb ?? string.Empty, 
			extraContext.Url ?? string.Empty, 
			extraContext.UserId ?? 0, 
			extraContext.UserCompanyId ?? 0);
	}
}
```

```
public class WebApiApplication : HttpApplication
{
	protected void Application_Start()
	{
		...
		
		PerfItRuntime.InstrumentorCreated += PerfItRuntime_InstrumentorCreated;

		var databaseListner = SqlDatabaseLog.CreateListener(
			"MyWebApi",
			ConfigurationManager.ConnectionStrings["TraceLogging"].ConnectionString);
			
		databaseListner.EnableEvents(SqlDatabaseEventSource.Instance, EventLevel.Informational, Keywords.All);
		
		...
	}
	
	private void PerfItRuntime_InstrumentorCreated(object instrumentor, InstrumentorCreatedArgs e)
	{
		e.Instrumentor.Tracers.Add("SqlDatabaseEventSourceTracer", new SqlDatabaseEventSourceTracer());
	}
}
```

```
public class TokenController : ApiController
{
    [PerfItFilter("MyWebApi", 
    Description = "MyWebApi Performance Counters", 
    InstrumentationContextProviderType = typeof(SqlDatabaseInstrumentationContextProvider))]
    public async Task<Token> DoLogin([FromBody] Credentials credentials)
    {
     ...
    }
}
```

![image](https://user-images.githubusercontent.com/1761025/38210452-24d8aff4-36c0-11e8-9916-a21f54a283b6.png)

![image](https://user-images.githubusercontent.com/1761025/38210604-8e8cead2-36c0-11e8-87f9-af8459c6ed2d.png)

**Comment by aliostad** [comment]
Hi,

I think you have done all fine but unfortunately EventSource is a peculiar thing. If you look closely in the output window of your Visual Studio, you will notice a line somewhere saying that your EventSource has incorrect parameter.

Essentially, EventSource requires you to have the exact signature in your decorate method (with Event attribute) as the parameters you send to `this.WriteEvent` - except the first parameter which is EventId. 

If you notice on my code, you will see that I have created an extension method to breakdown the context into its properties and pass them. So **your signature must like below** according to your parameters:

``` csharp
	[Event(42, Level = EventLevel.Informational)]
	public void WriteInstrumentationEvent(string categoryName,
		string instanceName,
		long timeTakenMilli,
		string correlationId = null,
		string httpVerb = null,
		string url = null, 
		int userId = 0, 
		int userCompanyId = 0)
	{
...
```
Use an extension method or a non-decorated method to do the breaking down.

**Comment by aliostad** [comment]
@valentinmarinro 
Another point is that the tracers are meant to buffer/batch their work on another thread not slowing down the actual code while they are writing to database or another store. I suggest you at least inherit from `SimpleTracerBase` which is simplistic but has a background thread and commits the traces on another thread.

**Comment by valentinmarinro** [comment]
@aliostad You were right, that was the issue, thanks a lot, I really appreciate all the time you spent helping me. Have a great day.

**Comment by aliostad** [comment]
@valentinmarinro not a problem at all. I am really pleased to see you are now on track to instrument your system.
