### ISSUE TITLE
Is PerfItDelegatingHandler obsolete?

### ISSUE THREAD

**Issue by ManojChala** [aliostad/PerfIt#76]
We are using Perfit in our project and I am trying to use the latest version from nuget. But I could not find this class PerfItDelegatingHandler. Could you please confirm whether this is obsolete, and if so, please let me know the alternative.

**Comment by aliostad** [comment]
In the recent version, the usage has been simplified by the use of filters. So yes, PerfItDelegatingHandler now has become [erfitClientDelegatingHandler](https://github.com/aliostad/PerfIt/blob/master/src/PerfIt.Http/PerfitClientDelegatingHandler.cs) for client scenarios but for Web API or server scenarios we have filters now.

There are examples here: https://github.com/aliostad/PerfIt/tree/master/samples
