### ISSUE TITLE
Support for arbitrary counter handler usage inside mvc actions or web api methods

### ISSUE THREAD

**Issue by aliozgur** [aliostad/PerfIt#8]
I think we can use the Disposable pattern (using) to enable arbitrary counter handler usage inside actions or web api methods. The major problem for this implementation is the discovery (install) part of the counters. But we can provide some abstract class which can be implemented just to define the counters. May be we can just use our filter attributes which will just become passive during the action/method invocation (just for counter discovery and install) and provide handy constructs for referencing inside action/webapi methods

**Comment by aliostad** [comment]
Hi,

This now possible with v1.0!
